import type {
  AppUser,
  ContractRecord,
  Customer,
  DeviceModel,
  Engineer,
  Installation,
  Machine,
  NotificationRecord,
  PMSSchedule,
  Ticket,
  TicketLog,
} from "@/types/service";

export const customers: Customer[] = [
  {
    CustomerID: "CUS-001",
    NameOfCustomer: "Kathmandu Heart Institute",
    HospitalName: "Kathmandu Heart Institute",
    Department: "Cath Lab",
    ContactPerson: "Dr. Mira Shrestha",
    Phone: "+977-9801000001",
    Email: "biomed@khi.example",
    Province: "Bagmati",
    District: "Kathmandu",
    Address: "Maharajgunj, Kathmandu",
    Latitude: "27.7361",
    Longitude: "85.3304",
    Remarks: "24/7 emergency cardiac center",
    CustomerType: "Hospital",
  },
  {
    CustomerID: "CUS-002",
    NameOfCustomer: "Pokhara Regional Hospital",
    HospitalName: "Pokhara Regional Hospital",
    Department: "Radiology",
    ContactPerson: "Suman Gurung",
    Phone: "+977-9801000002",
    Email: "radiology@prh.example",
    Province: "Gandaki",
    District: "Kaski",
    Address: "Lakeside Road, Pokhara",
    Latitude: "28.2096",
    Longitude: "83.9856",
    Remarks: "Prefers PMS visits before 11 AM",
    CustomerType: "Hospital",
  },
  {
    CustomerID: "CUS-003",
    NameOfCustomer: "Biratnagar Medical Centre",
    HospitalName: "Biratnagar Medical Centre",
    Department: "ICU",
    ContactPerson: "Anita Koirala",
    Phone: "+977-9801000003",
    Email: "icu@bmc.example",
    Province: "Koshi",
    District: "Morang",
    Address: "Main Road, Biratnagar",
    Latitude: "26.4525",
    Longitude: "87.2718",
    Remarks: "AMC customer",
    CustomerType: "Hospital",
  },
];

export const deviceModels: DeviceModel[] = [
  {
    ModelID: "MDL-001",
    BrandName: "Philips",
    Model: "IntelliVue MX450",
    PMSFrequency: "90",
    ImageURL: "",
  },
  {
    ModelID: "MDL-002",
    BrandName: "Siemens",
    Model: "Cios Select",
    PMSFrequency: "30",
    ImageURL: "",
  },
  {
    ModelID: "MDL-003",
    BrandName: "Drager",
    Model: "Evita V600",
    PMSFrequency: "90",
    ImageURL: "",
  },
];

export const installations: Installation[] = [
  {
    InstallationID: "INS-1001",
    CustomerID: "CUS-001",
    NameOfCustomer: "Kathmandu Heart Institute",
    Department: "ICU",
    ModelID: "MDL-001",
    Model: "IntelliVue MX450",
    BrandName: "Philips",
    SerialNumber: "PH-MX450-88421",
    InstallationDate: "2024-08-12",
    WarrantyYears: "3",
    WarrantyExpiry: "2027-08-11",
    Status: "Operational",
    Remarks: "ICU critical device",
    ImageURL: "",
  },
  {
    InstallationID: "INS-1002",
    CustomerID: "CUS-002",
    NameOfCustomer: "Pokhara Regional Hospital",
    Department: "Radiology",
    ModelID: "MDL-002",
    Model: "Cios Select",
    BrandName: "Siemens",
    SerialNumber: "SM-CIOS-33810",
    InstallationDate: "2022-01-18",
    WarrantyYears: "1",
    WarrantyExpiry: "2023-01-17",
    Status: "Operational",
    Remarks: "Monthly calibration required",
    ImageURL: "",
  },
  {
    InstallationID: "INS-1003",
    CustomerID: "CUS-003",
    NameOfCustomer: "Biratnagar Medical Centre",
    Department: "ICU",
    ModelID: "MDL-003",
    Model: "Evita V600",
    BrandName: "Drager",
    SerialNumber: "DR-EV600-77231",
    InstallationDate: "2023-11-02",
    WarrantyYears: "3",
    WarrantyExpiry: "2026-11-01",
    Status: "Attention",
    Remarks: "Repeat oxygen sensor alarms",
    ImageURL: "",
  },
];

export const amcContracts: ContractRecord[] = [];
export const cmcContracts: ContractRecord[] = [];
export const rrcContracts: ContractRecord[] = [];

export const machines: Machine[] = [
  {
    MachineID: "MAC-1001",
    CustomerID: "CUS-001",
    Department: "ICU",
    DeviceName: "Patient Monitor",
    Brand: "Philips",
    Model: "IntelliVue MX450",
    SerialNumber: "PH-MX450-88421",
    InstallationDate: "2024-08-12",
    WarrantyMonths: "36",
    WarrantyExpiry: "2027-08-11",
    ContractType: "Under Warranty",
    ContractStart: "2024-08-12",
    ContractEnd: "2027-08-11",
    PMSFrequency: "Quarterly",
    PMSIntervalDays: "90",
    LastPMS: "2026-03-10",
    NextPMS: "2026-06-10",
    Status: "Operational",
    Remarks: "ICU critical device",
    ImageURL: "",
  },
  {
    MachineID: "MAC-1002",
    CustomerID: "CUS-002",
    Department: "Radiology",
    DeviceName: "C-Arm",
    Brand: "Siemens",
    Model: "Cios Select",
    SerialNumber: "SM-CIOS-33810",
    InstallationDate: "2022-01-18",
    WarrantyMonths: "12",
    WarrantyExpiry: "2025-01-17",
    ContractType: "Under AMC",
    ContractStart: "2025-01-18",
    ContractEnd: "2027-01-17",
    PMSFrequency: "Monthly",
    PMSIntervalDays: "30",
    LastPMS: "2026-04-22",
    NextPMS: "2026-05-22",
    Status: "Operational",
    Remarks: "Monthly calibration required",
    ImageURL: "",
  },
  {
    MachineID: "MAC-1003",
    CustomerID: "CUS-003",
    Department: "ICU",
    DeviceName: "Ventilator",
    Brand: "Drager",
    Model: "Evita V600",
    SerialNumber: "DR-EV600-77231",
    InstallationDate: "2023-11-02",
    WarrantyMonths: "36",
    WarrantyExpiry: "2026-11-01",
    ContractType: "CMC",
    ContractStart: "2025-11-02",
    ContractEnd: "2028-11-01",
    PMSFrequency: "Quarterly",
    PMSIntervalDays: "90",
    LastPMS: "2026-02-19",
    NextPMS: "2026-05-19",
    Status: "Attention",
    Remarks: "Repeat oxygen sensor alarms",
    ImageURL: "",
  },
];

export const engineers: Engineer[] = [
  {
    EngineerID: "ENG-01",
    EngineerName: "Arjun Thapa",
    Phone: "+977-9802000001",
    Email: "arjun@wtc.example",
    Department: "Critical Care",
    Role: "Senior Engineer",
    ActiveStatus: "Available",
    LiveLatitude: "27.7109",
    LiveLongitude: "85.3220",
    LastLocationUpdate: new Date(Date.now() - 7 * 60000).toISOString(),
  },
  {
    EngineerID: "ENG-02",
    EngineerName: "Nisha Rai",
    Phone: "+977-9802000002",
    Email: "nisha@wtc.example",
    Department: "Radiology",
    Role: "Engineer",
    ActiveStatus: "On Visit",
    LiveLatitude: "28.2064",
    LiveLongitude: "83.9820",
    LastLocationUpdate: new Date(Date.now() - 3 * 60000).toISOString(),
  },
  {
    EngineerID: "ENG-03",
    EngineerName: "Bibek KC",
    Phone: "+977-9802000003",
    Email: "bibek@wtc.example",
    Department: "Installations",
    Role: "Engineer",
    ActiveStatus: "Available",
    LiveLatitude: "26.4611",
    LiveLongitude: "87.2768",
    LastLocationUpdate: new Date(Date.now() - 34 * 60000).toISOString(),
  },
];

export const tickets: Ticket[] = [
  {
    TicketID: "TKT-20260514-001",
    TicketDate: "2026-05-14",
    CustomerID: "CUS-001",
    MachineID: "MAC-1001",
    TicketTitle: "Intermittent SPO2 waveform drop",
    ProblemDescription: "Monitor intermittently loses SPO2 waveform during night shift.",
    ServiceType: "Breakdown (On-site Addressed)",
    Priority: "High",
    ContractType: "Under Warranty",
    AssignedEngineer: "ENG-01",
    AssistedBy: "ENG-03",
    TicketStatus: "Pending",
    ResponseType: "On-site",
    OpenedBy: "Manager",
    EngineerRemarks: "Probe and connector inspection started.",
    Resolution: "",
    VisitDate: "2026-05-14",
    CompletionDate: "",
    CustomerSignatureURL: "",
    AttachmentURLs: "",
    ClosureStatus: "Pending",
    Latitude: "27.7361",
    Longitude: "85.3304",
    LastUpdated: new Date(Date.now() - 16 * 60000).toISOString(),
  },
  {
    TicketID: "TKT-20260513-004",
    TicketDate: "2026-05-13",
    CustomerID: "CUS-002",
    MachineID: "MAC-1002",
    TicketTitle: "Monthly PMS and image quality check",
    ProblemDescription: "Scheduled PMS before orthopedic surgery camp.",
    ServiceType: "PMS",
    Priority: "Medium",
    ContractType: "Under AMC",
    AssignedEngineer: "ENG-02",
    AssistedBy: "",
    TicketStatus: "Pending",
    ResponseType: "Planned visit",
    OpenedBy: "Admin",
    EngineerRemarks: "",
    Resolution: "",
    VisitDate: "2026-05-16",
    CompletionDate: "",
    CustomerSignatureURL: "",
    AttachmentURLs: "",
    ClosureStatus: "Pending",
    Latitude: "28.2096",
    Longitude: "83.9856",
    LastUpdated: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    TicketID: "TKT-20260511-002",
    TicketDate: "2026-05-11",
    CustomerID: "CUS-003",
    MachineID: "MAC-1003",
    TicketTitle: "Oxygen sensor calibration completed",
    ProblemDescription: "Repeat low O2 alarm during ICU use.",
    ServiceType: "Application Issue",
    Priority: "Critical",
    ContractType: "CMC",
    AssignedEngineer: "ENG-03",
    AssistedBy: "",
    TicketStatus: "Closed",
    ResponseType: "On-site",
    OpenedBy: "Manager",
    EngineerRemarks: "Sensor calibrated, safety test passed.",
    Resolution: "Replaced inlet filter and calibrated oxygen sensor.",
    VisitDate: "2026-05-11",
    CompletionDate: "2026-05-12",
    CustomerSignatureURL: "",
    AttachmentURLs: "",
    ClosureStatus: "Ready for closure",
    Latitude: "26.4525",
    Longitude: "87.2718",
    LastUpdated: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
];

export const ticketLogs: TicketLog[] = [
  {
    LogID: "LOG-001",
    TicketID: "TKT-20260514-001",
    UpdatedBy: "Arjun Thapa",
    UpdateDate: new Date(Date.now() - 16 * 60000).toISOString(),
    Status: "Pending",
    Remarks: "Reached site and started diagnosis.",
    AttachmentURL: "",
    Latitude: "27.7361",
    Longitude: "85.3304",
  },
  {
    LogID: "LOG-002",
    TicketID: "TKT-20260513-004",
    UpdatedBy: "Nisha Rai",
    UpdateDate: new Date(Date.now() - 3 * 3600000).toISOString(),
    Status: "Pending",
    Remarks: "PMS tools and phantom kit prepared.",
    AttachmentURL: "",
    Latitude: "28.2064",
    Longitude: "83.9820",
  },
];

export const pmsSchedule: PMSSchedule[] = [
  {
    PMSID: "PMS-001",
    MachineID: "MAC-1002",
    CustomerID: "CUS-002",
    DueDate: "2026-05-22",
    AssignedEngineer: "ENG-02",
    Status: "Scheduled",
    CompletionDate: "",
    Remarks: "Coordinate with radiology in-charge",
  },
  {
    PMSID: "PMS-002",
    MachineID: "MAC-1003",
    CustomerID: "CUS-003",
    DueDate: "2026-05-19",
    AssignedEngineer: "ENG-03",
    Status: "Due",
    CompletionDate: "",
    Remarks: "Carry oxygen calibration kit",
  },
];

export const users: AppUser[] = [
  {
    UserID: "USR-ADMIN",
    Name: "WTC Admin",
    Email: "admin@wtc.local",
    Role: "Admin",
    ActiveStatus: "Active",
  },
  {
    UserID: "USR-MANAGER",
    Name: "Service Manager",
    Email: "manager@wtc.local",
    Role: "Manager",
    ActiveStatus: "Active",
  },
  {
    UserID: "USR-ENGINEER",
    Name: "Arjun Thapa",
    Email: "engineer@wtc.local",
    Role: "Engineer",
    EngineerID: "ENG-01",
    ActiveStatus: "Active",
  },
];

export const notifications: NotificationRecord[] = [
  {
    NotificationID: "NTF-001",
    Type: "Ticket assigned",
    Recipient: "arjun@wtc.example",
    Subject: "New high priority ticket assigned",
    Message: "Kathmandu Heart Institute needs SPO2 waveform support.",
    Status: "Sent",
    CreatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    SentAt: new Date(Date.now() - 19 * 60000).toISOString(),
  },
];
